nome = str(input("digite o seu nome = "))
cpf = str(input("digite o seu "))
rg = str(input("digite o = "))
datadenascimento = str(input("digite o = "))
sexo = str(input("digite o = "))
peso = str(input("digite o = "))
tiposanguíneo = str(input("digite o = "))
renda = str(input("digite o = "))
telefone = str(input("digite o = "))
endereço = str(input("digite o = ")) 
cidade = str(input("digite o = "))
estado = str(input("digite o = "))